# backend + frontend
# Pakai .env dari masing-masing folder (backend/.env, frontend/.env)
# DB_HOST di-override agar dari container bisa akses MySQL di host
# Jalankan: docker-compose up -d
# backend: http://localhost:8080
# frontend:    http://localhost:8081

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:80"
    env_file:
      - ./backend/.env
    environment:
      # Agar container bisa konek ke MySQL di host (Windows/Mac)
      DB_HOST: host.docker.internal
    volumes:
      - ./backend/storage:/var/www/html/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8079:80"
    env_file:
      - ./frontend/.env
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - ./frontend/storage:/var/www/html/storage
